config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  
  get '/users/sign_out' => 'devise/sessions#destroy'
  devise_for :users
  resources :users, only: [:index, :show, :destroy]
  get "users/:id/lock_user" => 'users#lock_user', as: 'lock_user'
  get "users/:id/unlock_user" => 'users#unlock_user', as: 'unlock_user'

  get 'pages/info'

  get 'x3dom' => "x3dom#index"

  resources :ideas do
    resources :comments#, only: [ :create, :destroy ]#später: edit, update wenn nutzerspezifische Kommentare möglich
  end

  root to: redirect('ideas')
  

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  #erst alle Comments löschen, um nicht zugewiesene comments zu verhindern
  has_many :comments, dependent: :destroy
  validates :name, presence:true
  validates :description, presence:true
  belongs_to :user
end

# == Schema Information
#
# Table name: ideas
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :text
#  picture     :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer
#

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  load_and_authorize_resource

  # GET /ideas
  # GET /ideas.json
  def index
    @current_ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @current_idea = Idea.new
  end
    
  # GET /ideas/1/edit
  def edit
  end
  # POST /ideas
  # POST /ideas.json
  def create
    @current_idea = Idea.new(idea_params)
    current_idea.user_id = current_user.id

    respond_to do |format|
      if current_idea.save
        format.html { redirect_to current_idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: current_idea }
      else
        format.html { render :new }
        format.json { render json: current_idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if current_idea.update(idea_params)
        format.html { redirect_to current_idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: current_idea }
      else
        format.html { render :edit }
        format.json { render json: current_idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    current_idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def current_idea
      @current_idea ||= Idea.find(params[:id])
    end
    helper_method :current_idea

    def current_ideas
      @current_ideas ||= Idea.all
    end
    helper_method :current_ideas

    def current_comments
      @current_comments = current_idea.comments.all
    end
    helper_method :current_comments


    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:user_name, :name, :description, :picture)
    end

end

app/helpers/ideas_helper.rb
module IdeasHelper
  def show_idea_image(idea, width: 100)
    show_image(idea, width: width)
  end

end

app/views/ideas/_form.html.haml
= form_for current_idea, html: {multipart: true} do |f|
  - if current_idea.errors.any?
    .error_explanation
      %h2= pluralize(current_idea.errors.count, "error") 
      prohibited this idea from being saved
      %ul
      - current_idea.errors.full_messages.each do |message|
        %li= message
  .field
    = f.label :name
    = f.text_field :name
  %br
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :picture
    = show_idea_image(current_idea, width: 150)
    %br
    = f.file_field :picture, accept: "image/*" #nur Bilddateien anzeigen! (erzeugter html-Code: 'accept="image/*"'

  %br
  .actions
    = f.submit t('.submit')
/debug action_name       - gibt aktuelle Action wieder(new, edit)
/debug controller_name   - gibt aktuellen controller wieder (ideas in diesem Fall)

app/views/ideas/_idea.html.haml
.span4.idea{class: "idea-#{idea.id}"}
  = show_idea_image(idea, width:100)
  %h4= link_to idea.name, idea
  = idea.description

app/views/ideas/edit.html.haml
%h2= t '.headline'
= render 'form'
= link_to t(:back), ideas_path

app/views/ideas/index.html.haml
%h2=t '.headline' #:index, scope: [:ideas]

- current_ideas.in_groups_of(3,false) do |group|
  .row
    = render group #.each do |idea|
    /.span4
    / = show_idea_image(idea, width:100)
    /%h4= link_to idea.name, idea
    /= idea.description

app/views/ideas/new.html.haml
%h2= t '.headline' #New idea
= render 'form'
= link_to t('back'), ideas_path

app/views/ideas/show.html.haml
.row  
  /image_tag("arrow-previous.jpeg", width:25)
  %p= link_to t('back'), ideas_path
  %table.border{border:"1"}
    %td.border
      %table
        %tr
          %td
            = show_image(current_idea.user, width:20)
            %b
              - if can? :show, current_idea.user
                = link_to current_idea.user.name, current_idea.user
              - else  
                = current_idea.user.name
          %td{align:"right"}= format_date(current_idea.user.created_at)
        %tr
          %td{colspan:"2"}
            %h4= current_idea.name 
        %tr
          %td= show_idea_image(current_idea, width: 100)
          %td{valign:"top"}
            %p= current_idea.description
      %br
      = t '.last_edited' 
      = format_date(current_idea.user.updated_at)
      %br
      = link_to t('edit'), edit_idea_path(current_idea) if can? :update, current_idea
      = link_to t('delete'), current_idea, method: :delete, data: { confirm: 'Are you sure?' } if can? :delete, current_idea
  /Content für Kommentare
  %h4= t '.comments'
  = render current_idea.comments
  = render "comments/form", current_comment: current_idea.comments.new