config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  
  get '/users/sign_out' => 'devise/sessions#destroy'
  devise_for :users
  resources :users, only: [:index, :show, :destroy]
  get "users/:id/lock_user" => 'users#lock_user', as: 'lock_user'
  get "users/:id/unlock_user" => 'users#unlock_user', as: 'unlock_user'

  get 'pages/info'

  get 'x3dom' => "x3dom#index"

  resources :ideas do
    resources :comments#, only: [ :create, :destroy ]#später: edit, update wenn nutzerspezifische Kommentare möglich
  end

  root to: redirect('ideas')
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
  belongs_to :user
  validates :user, presence:true
  validates :body, presence:true

  def user_name
    user.name
  end
end

# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  idea_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  # GET /comments
  # GET /comments.json
  def index
  end

  # GET ideas/1/comments/1
  # GET ideas/1/comments/1.json
  def show    
  end

  # GET ideas/1/comments/new
  def new
    @current_comment = current_idea.comments.new(user: current_user)
  end

  # GET ideas/1/comments/1/edit
  def edit
  end

  # POST ideas/1/comments
  # POST ideas/1/comments.json
  def create
    @current_comment = current_idea.comments.new(comment_params)
    @current_comment.user = current_user

    respond_to do |format|
      if current_comment.save
        format.html { redirect_to current_comment.idea, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: current_comment.idea }
      else
        format.html { render :new }
        format.json { render json: current_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT ideas/1/comments/1
  # PATCH/PUT ideas/1/comments/1.json
  def update
    respond_to do |format|
      if current_comment.update(comment_params)
        format.html { redirect_to current_comment.idea, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: current_comment.idea }
      else
        format.html { render :edit }
        format.json { render json: current_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE ideas/1/comments/1
  # DELETE ideas/1/comments/1.json
  def destroy
    @current_comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def current_comment
      @current_comment ||= current_idea.comments.find(params[:id])
    end
    helper_method :current_comment

    def current_idea
      @current_idea ||= Idea.find(params[:idea_id]) #method cashing: hole idea vom Parameter oder, wenn vorhanden, nimm die vorhandene idea
    end
    helper_method :current_idea #current_idea 

    def current_comments
      @current_comments ||= current_idea.comments
    end
    helper_method :current_comments

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
.comment
  = show_image(comment.user, width:20)
  %b
    - if can? :show, comment.user
      = link_to comment.user_name, comment.user
    - else
      = comment.user_name
  %br
  %p= comment.body
  %p
    = link_to t('edit'), edit_idea_comment_path(current_idea, comment) if can? :update, comment
    = link_to t('delete'), idea_comment_path(current_idea, comment), method: :delete, data: { confirm: t('confirm')} if can? :delete, comment

app/views/comments/_form.html.erb
<%- if can? :create, Comment %>
  <%= form_for [current_comment.idea, current_comment] do |f| %>
    <% if f.object.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(f.object.errors.count, "error") %> prohibited this comment from being saved:</h2>

        <ul>
        <% f.object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :body, t('.write_new_comment') %>
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit t('.submit') %>
    </div>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<h2><%= t '.headline' %></h2>

<%= render 'form' %>

<%= link_to t('back'), idea_path(current_comment.idea) %>

app/views/comments/index.html.erb
<h2><%= t '.headline' %></h2>

<table>
  <thead>
    <tr>
      <th><%= t 'comments.user_name' %></th>
      <th><%= t 'comments.body' %></th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% current_comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= link_to t('show'), idea_comment_path(comment.idea_id, comment) %></td>
        <% if can? :update, comment %>
          <td><%= link_to t('edit'), edit_idea_comment_path(comment.idea_id, comment) %></td>
        <% end %>
        <% if can? :delete, comment %>
          <td><%= link_to t('delete'), idea_comment_path(comment.idea_id, comment), method: :delete, data: { confirm: t('confirm') } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new_comment'), new_idea_comment_path(current_idea) %>

app/views/comments/new.html.erb
<h2><%= t '.headline' %></h2>

<%= render 'form' %>

<%= link_to t('back'), idea_comments_path %>

app/views/comments/show.html.erb
<p>
  <strong><%= t('comments.user_name') %>:</strong>
  <%= current_comment.user_name %>
</p>

<p>
  <strong><%= t('comments.body') %>:</strong>
  <%= current_comment.body %>
</p>

<%= link_to t('edit'), edit_idea_comment_path(current_comment.idea_id, current_comment) %> |
<%=  link_to t('delete'), idea_comment_path(current_comment.idea_id, current_comment), method: :delete, data: { confirm: t('confirm') } %> |
<%= link_to t('back'), idea_comments_path(current_comment.idea_id) %>