config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  
  get '/users/sign_out' => 'devise/sessions#destroy'
  devise_for :users
  resources :users, only: [:index, :show, :destroy]
  get "users/:id/lock_user" => 'users#lock_user', as: 'lock_user'
  get "users/:id/unlock_user" => 'users#unlock_user', as: 'unlock_user'

  get 'pages/info'

  get 'x3dom' => "x3dom#index"

  resources :ideas do
    resources :comments#, only: [ :create, :destroy ]#später: edit, update wenn nutzerspezifische Kommentare möglich
  end

  root to: redirect('ideas')
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :picture, PictureUploader
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, 
         #authentication_keys: [:name]
  has_many :ideas, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, uniqueness: { case_sensitive: false }

  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || name || email
  end

  def admin?
     name == "Admin" && id == 15
     #passwort: werbeboten
     #email: admin@admin.de
  end

#necessary for user login by email OR name
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(name) = :value OR lower(email) = :value", { value: login.downcase }]).first
    else
      where(conditions).first
    end
  end

end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  name                   :string(255)
#  picture                :string(255)
#  locked                 :boolean
#

app/controllers/users_controller.rb
# -*- encoding : utf-8 -*-
class UsersController < ApplicationController#Devise::RegistrationsController
  load_and_authorize_resource

  def index
  end

  def show
  end

  def destroy
    current_user_profile.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'User was succesesfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def lock_user 
    current_user_profile.locked = true
    current_user_profile.save
    redirect_to user_path(current_user_profile)
  end

  def unlock_user
    current_user_profile.locked = false
    current_user_profile.save
    redirect_to user_path(current_user_profile)
  end

  def current_user_profile
    @current_user_profile ||= User.find(params[:id])
  end
  helper_method :current_user_profile

  def user_profiles
    @user_profiles ||= User.all
  end
  helper_method :user_profiles

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.haml
.user
  = show_image(user, width:100)
  - if user.locked?
    = t('.locked')
  %br
  - if can? :read_id, user
    ID: #{user.id}
    %br
  - if can? :read_email, user || user == current_user
    = t('.email') + ':'
    = mail_to user.email, user.email
  - if can? :update, user
    %br
    = link_to t('.edit', name: user.name), edit_user_registration_path
  %br
  - if current_user && current_user.admin?
    - unless user.locked
      = link_to t('.lock', name: user.name), lock_user_path(user.id)
    - else
      = link_to t('.unlock', name: user.name), unlock_user_path(user.id)
    %br
    = link_to t('.delete', name: user.name), user_path(user), data: {confirm: t('.confirm', name: user.name)}, method: :delete

app/views/users/index.html.haml
%h3= t('.headline')
- user_profiles.in_groups_of(3,false) do |user_group|
  .span5
    - user_group.each do |user|
      %h3= link_to user.name, user
      = render user
      %p
        .ideas
          = t 'users.idea_list', name: user.name
          - user.ideas.each do |idea|
            .idea
              = link_to idea.name, idea
              %br

app/views/users/show.html.haml
%p
  %h3= current_user_profile.name
  = render current_user_profile
%p
  - if current_user_profile.ideas.count > 0
    %h4= t('users.idea_list', name: current_user_profile.name)
    = render current_user_profile.ideas