config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/railsadmin', as: 'rails_admin'
  
  get '/users/sign_out' => 'devise/sessions#destroy'
  devise_for :users
  resources :users, only: [:index, :show, :destroy]
  get "users/:id/lock_user" => 'users#lock_user', as: 'lock_user'
  get "users/:id/unlock_user" => 'users#unlock_user', as: 'unlock_user'

  get 'pages/info'

  get 'x3dom' => "x3dom#index"

  resources :ideas do
    resources :comments#, only: [ :create, :destroy ]#später: edit, update wenn nutzerspezifische Kommentare möglich
  end

  root to: redirect('ideas')
  

end

app/views/shared/_footer.html.haml
%footer.container{align: "center"}
  %ul.always-visible
    %li
      Idea Manager 2014
      |
    %li
      = t('.created_by', name: "Benjamin Schäfer")
      |
    %li
      = link_to t('.about'), pages_info_path

app/views/shared/_menu.html.haml
.container
  %ul#list-nav.always-visible
    %li
      = link_to t('.ideas'), ideas_path
    - if can? :create, Idea
      %li
        = link_to t('.new_idea'), new_idea_path 
    - if can? :index, User
      %li
        = link_to t('.users_list'), users_path 
    - if current_user && current_user.admin?
      %li
        = link_to t('.admin'), rails_admin_path
    /show | edit profile
    - if user_signed_in?
      %li 
        = link_to t('.edit_profile'), edit_user_registration_path, class: 'navbar-link'
      %li
        = link_to t('.logout'), destroy_user_session_path, method: :delete, class: 'navbar-link'
      /sign up | Login
    - else 
      %li  
        = link_to t('.signup'), new_user_registration_path, class: 'navbar-link'
      %li
        = link_to t('.login'), new_user_session_path, class: 'navbar-link'

    - if user_signed_in?
      %li.user
        = link_to show_image(current_user, width:20) + " #{current_user.name}", user_path(current_user)